"""add_invitation_token_to_notifications

Revision ID: 677bac2fff24
Revises: c693c49df7bf
Create Date: 2026-04-25 18:06:51.230740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión — NO modificar manualmente
revision: str = '677bac2fff24'
down_revision: Union[str, None] = 'c693c49df7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema de la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('invitation_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de upgrade() — retrocede una versión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'invitation_token')
    # ### end Alembic commands ###
