"""add_teacher_feedback_to_projects

Revision ID: d5859afe105a
Revises: 677bac2fff24
Create Date: 2026-04-28 20:58:49.352187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión — NO modificar manualmente
revision: str = 'd5859afe105a'
down_revision: Union[str, None] = '677bac2fff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema de la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('teacher_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios de upgrade() — retrocede una versión."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'teacher_feedback')
    # ### end Alembic commands ###
